POST http://localhost:3060/message
Content-Type: multipart/form-data;

{
    "file":"./perrogracioso.jpg",
    "user": "6471e9d6b01b6c1db6a6b99d",
    "chat": "6471ea18b01b6c1db6a6b9a2",
    "message": "Mira este perro actualizado desde ws"
}