POST http://localhost:3060/message
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2IzMDdjZmQwYzFlNTU1NmNlODIxOSIsImlhdCI6MTY4NTc5NDk2NywiZXhwIjoxNjg2Mzk5NzY3fQ.Ho_I2TVXYe-GXIeh5QsKe7PAwPejPfoJ7zolCx6A6ro

{
    "chat": "647c5dc9b1d16ba8bcc55c43",
    "message": "integrando DB con WS2"
}



###
PATCH http://localhost:3060/message/646f68376121457155731e70
Content-Type: application/json

{
    "message": "mirando response"
}