POST http://localhost:3060/message
Content-Type: application/json

{
    "user": "6471e9d6b01b6c1db6a6b99d",
    "chat": "6471ea18b01b6c1db6a6b9a2",
    "message": "probando WS2"
}
###
PATCH http://localhost:3060/message/646f68376121457155731e70
Content-Type: application/json

{
    "message": "mirando response"
}