POST http://localhost:3060/message
Content-Type: application/json

{
    "user": "Nicolas Martinez",
    "message": "agregando a list"
}
###
PATCH http://localhost:3060/message/646f68376121457155731e70
Content-Type: application/json

{
    "message": "mirando response"
}